"""Synthesize actionable markdown guidance from behavioral analysis.

Generates CLAUDE.md / AGENTS.md / TRACEOPS_GUIDANCE.md style documents
from PatternReport or GapReport objects — directly inspired by agent-pr-replay's
``analyzer.generate_report`` step that produces steering rules from observed
behavioral gaps between AI agents and human solutions.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .gap_analyzer import GapReport
from .pattern_detector import PatternReport

_REPO_URL = "https://github.com/ioteverythin/project_dragon"


class SkillsGenerator:
    """Synthesize actionable markdown guidance from TraceOps analysis results.

    Example::

        gen = SkillsGenerator()
        md = gen.from_gap_report(report)
        Path("AGENTS.md").write_text(md)
    """

    def from_gap_report(
        self,
        report: GapReport,
        output_path: Path | None = None,
        title: str = "TraceOps Behavioral Guidance",
    ) -> str:
        """Generate guidance markdown from a :class:`~.gap_analyzer.GapReport`."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines: list[str] = [
            f"# {title}",
            "",
            f"> Auto-generated by TraceOps on {now}.  ",
            (
                f"> Compared **{report.golden_count}** golden traces vs "
                f"**{report.agent_count}** agent traces.  "
            ),
            (
                f"> Found **{len(report.gaps)}** behavioral gap(s) "
                f"({report.critical_count} critical, {report.warning_count} warnings)."
            ),
            "",
        ]

        if not report.gaps:
            lines += [
                "## ✅ No Significant Gaps Found",
                "",
                "Agent behavior is aligned with the golden baseline.",
            ]
        else:
            by_category: dict[str, list] = {}
            for gap in report.gaps:
                by_category.setdefault(gap.category, []).append(gap)

            _labels = {
                "token_inflation": "## ⚠️ Token Usage",
                "cost_inflation": "## 💸 Cost Efficiency",
                "missing_tool": "## 🔧 Missing Tool Usage",
                "extra_tool": "## 🔧 Excessive Tool Usage",
                "model_mismatch": "## 🤖 Model Selection",
                "error_rate": "## 🚨 Error Rate",
                "llm_call_inflation": "## 📞 LLM Call Frequency",
            }
            _icons = {"critical": "🔴", "warning": "🟡", "info": "🔵"}

            for cat, gaps in by_category.items():
                label = _labels.get(cat, f"## {cat.replace('_', ' ').title()}")
                lines += ["", label, ""]
                for gap in gaps:
                    icon = _icons.get(gap.severity, "•")
                    lines.append(f"- {icon} **[{gap.severity.upper()}]** {gap.description}")
                    if gap.golden_value is not None and gap.agent_value is not None:
                        lines.append(
                            f"  - Golden baseline: `{gap.golden_value}` "
                            f"| Agent: `{gap.agent_value}`"
                        )
                    if gap.frequency < 1.0:
                        lines.append(
                            f"  - Affects {gap.frequency * 100:.0f}% of agent traces"
                        )

        lines += ["", "---", f"_Generated by [TraceOps]({_REPO_URL})_"]
        md = "\n".join(lines)
        if output_path is not None:
            Path(output_path).write_text(md, encoding="utf-8")
        return md

    def from_pattern_report(
        self,
        report: PatternReport,
        output_path: Path | None = None,
        title: str = "TraceOps Pattern Summary",
    ) -> str:
        """Generate a behavioral summary markdown from a
        :class:`~.pattern_detector.PatternReport`."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines: list[str] = [
            f"# {title}",
            "",
            f"> Auto-generated by TraceOps on {now}.  ",
            (
                f"> Analyzed **{report.cassette_count}** traces "
                f"({report.total_events} total events)."
            ),
            "",
            "## 📊 Averages per Trace",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| LLM calls | {report.avg_llm_calls:.1f} |",
            f"| Tokens | {report.avg_tokens:.0f} |",
            f"| Cost | ${report.avg_cost_usd:.5f} |",
            "",
        ]

        if report.top_tool_sequences:
            lines += ["## 🔁 Common Tool Sequences", ""]
            for i, seq in enumerate(report.top_tool_sequences[:5], 1):
                arrow = " → ".join(seq.sequence)
                lines.append(
                    f"{i}. `{arrow}` — seen **{seq.count}×** "
                    f"across {len(seq.cassettes)} cassette(s)"
                )
            lines.append("")

        if report.tool_frequency:
            lines += ["## 🛠️ Tool Usage Frequency", ""]
            for tool, count in sorted(
                report.tool_frequency.items(), key=lambda x: -x[1]
            )[:10]:
                lines.append(f"- `{tool}`: {count} call(s)")
            lines.append("")

        if report.model_usage:
            lines += ["## 🤖 Model Usage", ""]
            for m in report.model_usage[:5]:
                lines.append(
                    f"- `{m.model}`: {m.call_count} call(s), "
                    f"{m.total_tokens:,} tokens, ${m.total_cost_usd:.5f}"
                )
            lines.append("")

        if report.most_common_errors:
            lines += ["## 🚨 Common Errors", ""]
            for err, cnt in report.most_common_errors[:5]:
                lines.append(f"- `{err}`: {cnt}×")
            lines.append("")

        lines += ["---", f"_Generated by [TraceOps]({_REPO_URL})_"]
        md = "\n".join(lines)
        if output_path is not None:
            Path(output_path).write_text(md, encoding="utf-8")
        return md
