"""HTML trace report — generate a shareable single-file HTML report.

Produces a self-contained HTML document (inline CSS/JS, no external
dependencies) that visualises a recorded trace as an interactive
timeline.  Can be attached to PRs, pasted into Slack, or opened
directly in a browser.

Usage::

    from trace_ops.reporters.html import generate_html_report
    generate_html_report(trace, "report.html")

CLI::

    replay report cassettes/test_math.yaml -o report.html
"""

from __future__ import annotations

import html
import json
from pathlib import Path

from trace_ops._types import EventType, Trace, TraceEvent


def generate_html_report(
    trace: Trace,
    output_path: str | Path,
    *,
    compare_trace: Trace | None = None,
    title: str = "TraceOps Trace Report",
) -> Path:
    """Generate a single-file HTML trace report.

    Args:
        trace: The primary trace to visualise.
        output_path: Where to write the HTML file.
        compare_trace: Optional second trace for diff overlay.
        title: Page title.

    Returns:
        The resolved output path.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    body = _build_html(trace, compare_trace=compare_trace, title=title)
    output_path.write_text(body, encoding="utf-8")
    return output_path


# ── HTML builder ────────────────────────────────────────────────────

_EVENT_COLOURS: dict[str, str] = {
    "llm_request": "#3b82f6",   # blue
    "llm_response": "#22c55e",  # green
    "tool_call": "#eab308",     # yellow
    "tool_result": "#f59e0b",   # amber
    "agent_decision": "#a855f7",  # purple
    "error": "#ef4444",         # red
}


def _build_html(
    trace: Trace,
    *,
    compare_trace: Trace | None,
    title: str,
) -> str:
    summary_html = _build_summary(trace)
    trajectory_html = _build_trajectory(trace)
    events_html = _build_events(trace)
    cost_html = _build_cost_chart(trace)
    diff_html = _build_diff_section(trace, compare_trace) if compare_trace else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>
{_CSS}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>🔁 {html.escape(title)}</h1>
    <p class="subtitle">Generated by TraceOps v0.5.0</p>
  </header>

  <section class="summary">{summary_html}</section>
  <section class="trajectory"><h2>Trajectory</h2>{trajectory_html}</section>
  <section class="cost-chart"><h2>Token &amp; Cost Breakdown</h2>{cost_html}</section>
  {f'<section class="diff"><h2>Diff</h2>{diff_html}</section>' if diff_html else ''}
  <section class="events"><h2>Events ({len(trace.events)})</h2>{events_html}</section>
</div>
<script>
{_JS}
</script>
</body>
</html>"""


def _build_summary(trace: Trace) -> str:
    return f"""
<div class="stats-grid">
  <div class="stat"><span class="stat-value">{trace.total_llm_calls}</span><span class="stat-label">LLM Calls</span></div>
  <div class="stat"><span class="stat-value">{trace.total_tool_calls}</span><span class="stat-label">Tool Calls</span></div>
  <div class="stat"><span class="stat-value">{trace.total_tokens:,}</span><span class="stat-label">Tokens</span></div>
  <div class="stat"><span class="stat-value">${trace.total_cost_usd:.4f}</span><span class="stat-label">Cost</span></div>
  <div class="stat"><span class="stat-value">{trace.total_duration_ms:.0f}ms</span><span class="stat-label">Duration</span></div>
  <div class="stat"><span class="stat-value mono">{trace.fingerprint()[:12]}</span><span class="stat-label">Fingerprint</span></div>
</div>"""


def _build_trajectory(trace: Trace) -> str:
    if not trace.trajectory:
        return "<p class='dim'>No trajectory recorded.</p>"
    steps = []
    for _i, step in enumerate(trace.trajectory):
        kind = step.split(":")[0]
        colour = _EVENT_COLOURS.get(
            {"llm_call": "llm_request", "tool": "tool_call", "decision": "agent_decision", "error": "error"}.get(kind, ""),
            "#888",
        )
        steps.append(
            f'<span class="traj-step" style="border-color:{colour}">'
            f"{html.escape(step)}</span>"
        )
    return '<div class="traj-flow">' + ' <span class="traj-arrow">→</span> '.join(steps) + "</div>"


def _build_events(trace: Trace) -> str:
    parts: list[str] = []
    for i, event in enumerate(trace.events, 1):
        colour = _EVENT_COLOURS.get(event.event_type.value, "#888")
        label = event.event_type.value.replace("_", " ").title()
        model_or_tool = event.model or event.tool_name or event.decision or ""

        tokens = ""
        if event.input_tokens or event.output_tokens:
            tokens = f"{event.input_tokens or 0} / {event.output_tokens or 0} tokens"

        duration = f"{event.duration_ms:.0f}ms" if event.duration_ms else ""

        detail = _event_detail(event)

        parts.append(f"""
<details class="event">
  <summary>
    <span class="event-num">#{i}</span>
    <span class="event-badge" style="background:{colour}">{html.escape(label)}</span>
    <span class="event-name">{html.escape(model_or_tool)}</span>
    <span class="event-meta">{html.escape(tokens)}</span>
    <span class="event-meta">{html.escape(duration)}</span>
  </summary>
  <div class="event-detail">{detail}</div>
</details>""")

    return "\n".join(parts)


def _event_detail(event: TraceEvent) -> str:
    sections: list[str] = []

    if event.messages:
        msgs = ""
        for msg in event.messages:
            role = msg.get("role", "?")
            content = str(msg.get("content", ""))[:1000]
            msgs += f"<div class='msg'><strong>{html.escape(role)}</strong>: {html.escape(content)}</div>"
        sections.append(f"<div class='msg-list'>{msgs}</div>")

    if event.response:
        try:
            resp_str = json.dumps(event.response, indent=2, ensure_ascii=False, default=str)[:2000]
        except (TypeError, ValueError):
            resp_str = str(event.response)[:2000]
        sections.append(f"<pre class='response-json'>{html.escape(resp_str)}</pre>")

    if event.tool_input:
        try:
            inp = json.dumps(event.tool_input, indent=2, default=str)[:1000]
        except (TypeError, ValueError):
            inp = str(event.tool_input)[:1000]
        sections.append(f"<div><strong>Input:</strong><pre>{html.escape(inp)}</pre></div>")

    if event.tool_output:
        out = str(event.tool_output)[:1000]
        sections.append(f"<div><strong>Output:</strong><pre>{html.escape(out)}</pre></div>")

    if event.decision:
        sections.append(f"<div><strong>Decision:</strong> {html.escape(event.decision)}</div>")
    if event.reasoning:
        sections.append(f"<div><strong>Reasoning:</strong> {html.escape(event.reasoning)}</div>")

    if event.error_type:
        sections.append(
            f"<div class='error-detail'><strong>{html.escape(event.error_type)}:</strong> "
            f"{html.escape(str(event.error_message))}</div>"
        )

    if event.metadata:
        try:
            meta_str = json.dumps(event.metadata, indent=2, default=str)[:500]
        except (TypeError, ValueError):
            meta_str = str(event.metadata)[:500]
        sections.append(f"<div class='dim'><strong>Metadata:</strong><pre>{html.escape(meta_str)}</pre></div>")

    return "\n".join(sections) if sections else "<em>No details.</em>"


def _build_cost_chart(trace: Trace) -> str:
    """Build a simple CSS bar chart showing per-call token usage."""
    llm_events = [
        e for e in trace.events if e.event_type == EventType.LLM_RESPONSE
    ]
    if not llm_events:
        return "<p class='dim'>No LLM calls to chart.</p>"

    max_tokens = max(
        (e.input_tokens or 0) + (e.output_tokens or 0) for e in llm_events
    ) or 1

    bars: list[str] = []
    for i, e in enumerate(llm_events, 1):
        inp = e.input_tokens or 0
        out = e.output_tokens or 0
        total = inp + out
        pct = (total / max_tokens) * 100
        cost_str = f"${e.cost_usd:.4f}" if e.cost_usd else ""
        bars.append(
            f'<div class="bar-row">'
            f'<span class="bar-label">Call {i} ({html.escape(e.model or "?")})</span>'
            f'<div class="bar-track">'
            f'<div class="bar-fill" style="width:{pct:.1f}%">{total:,}</div>'
            f'</div>'
            f'<span class="bar-cost">{cost_str}</span>'
            f'</div>'
        )

    return '<div class="bar-chart">' + "\n".join(bars) + "</div>"


def _build_diff_section(trace: Trace, compare: Trace) -> str:
    from trace_ops.diff import diff_traces

    diff = diff_traces(trace, compare)
    if not diff.has_changes:
        return "<p class='success'>✅ Traces are identical.</p>"
    return f"<pre class='diff-output'>{html.escape(diff.summary())}</pre>"


# ── Inline CSS ──────────────────────────────────────────────────────

_CSS = """
:root { --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #e6edf3;
  --dim: #8b949e; --accent: #58a6ff; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.6; }
.container { max-width: 960px; margin: 0 auto; padding: 2rem 1rem; }
header { margin-bottom: 2rem; }
h1 { font-size: 1.6rem; }
h2 { font-size: 1.2rem; margin-bottom: 1rem; color: var(--accent); }
.subtitle { color: var(--dim); font-size: 0.85rem; }
section { margin-bottom: 2rem; }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
  gap: 0.75rem; }
.stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
  padding: 1rem; text-align: center; }
.stat-value { display: block; font-size: 1.4rem; font-weight: 600; color: var(--accent); }
.stat-label { display: block; font-size: 0.75rem; color: var(--dim); margin-top: 0.25rem; }
.mono { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 0.9rem; }
.dim { color: var(--dim); }

/* Trajectory */
.traj-flow { display: flex; flex-wrap: wrap; align-items: center; gap: 0.4rem; }
.traj-step { padding: 0.25rem 0.6rem; border: 2px solid; border-radius: 6px;
  font-size: 0.8rem; font-family: monospace; background: var(--card); }
.traj-arrow { color: var(--dim); font-weight: bold; }

/* Events */
.event { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
  margin-bottom: 0.5rem; }
.event summary { padding: 0.75rem 1rem; cursor: pointer; display: flex;
  align-items: center; gap: 0.75rem; font-size: 0.9rem; }
.event summary:hover { background: rgba(255,255,255,0.03); }
.event-num { color: var(--dim); min-width: 2.5rem; font-family: monospace; }
.event-badge { color: #fff; padding: 0.15rem 0.5rem; border-radius: 4px;
  font-size: 0.75rem; font-weight: 600; white-space: nowrap; }
.event-name { font-weight: 500; }
.event-meta { color: var(--dim); font-size: 0.8rem; margin-left: auto; white-space: nowrap; }
.event-detail { padding: 0.75rem 1rem; border-top: 1px solid var(--border);
  font-size: 0.85rem; }
.event-detail pre { background: var(--bg); padding: 0.75rem; border-radius: 6px;
  overflow-x: auto; font-size: 0.8rem; margin: 0.5rem 0; white-space: pre-wrap; word-break: break-word; }
.msg { margin-bottom: 0.5rem; }
.error-detail { color: #ef4444; }
.success { color: #22c55e; }

/* Bar chart */
.bar-chart { display: flex; flex-direction: column; gap: 0.4rem; }
.bar-row { display: flex; align-items: center; gap: 0.5rem; }
.bar-label { min-width: 180px; font-size: 0.8rem; color: var(--dim); text-align: right; }
.bar-track { flex: 1; height: 22px; background: var(--bg); border-radius: 4px; overflow: hidden; }
.bar-fill { height: 100%; background: var(--accent); border-radius: 4px;
  display: flex; align-items: center; padding-left: 0.5rem;
  font-size: 0.7rem; font-weight: 600; min-width: fit-content; }
.bar-cost { min-width: 70px; font-size: 0.8rem; color: var(--dim); }

.diff-output { background: var(--card); padding: 1rem; border-radius: 8px;
  font-size: 0.85rem; white-space: pre-wrap; }
"""

_JS = """
// Collapse all events by default — already handled by <details>
document.querySelectorAll('.event').forEach(el => el.removeAttribute('open'));
"""
